### ISSUE TITLE
help

### ISSUE THREAD

**Issue by z-ffqq** [MrSpidercat/Matu#2]
cat became obese because of this theme

you suck!!!! (i am angyr)

**Comment by z-ffqq** [comment]
please help my cat just turned into a dog

**Comment by z-ffqq** [comment]
help my dog is turning into a wolf

**Comment by z-ffqq** [comment]
help

**Comment by z-ffqq** [comment]
i am dying

**Comment by z-ffqq** [comment]
i am dead now

**Comment by MrSpidercat** [comment]
...
